spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-web?currentSchema=public
    username: postgres
    password: andrei16
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # the first time you should replace "validate" with "create" so it makes the schema and then leave is a "validate"
    show-sql: false
    properties:
      hibernate:
        jdbc:
            lob:
                non_contextual_creation: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

server:
  port: 4000
